<div class="slideshow_container">
	<!--- Slideshow stuff goes here -->
	<div id="slides">
	  <div class="slides_container">

		<div>
		  <img src="<?php echo get_stylesheet_directory_uri() ?>/slideshow/website pic 2.jpg" width="922" height="279" alt="Slide 1">
		</div>

		<div>		
		  <img src="<?php echo get_stylesheet_directory_uri() ?>/slideshow/website pic 3.jpg" width="922" height="279" alt="Slide 1">
		</div>

		<div>
		  <img src="<?php echo get_stylesheet_directory_uri() ?>/slideshow/website pic 4.jpg" width="922" height="279" alt="Slide 1">
		</div>

		<div>
		  <img src="<?php echo get_stylesheet_directory_uri() ?>/slideshow/website pic 5.jpg" width="922" height="279" alt="Slide 1">
		</div>

	  </div>
	</div>
	<!-- End slideshow stuff -->
</div>
