<div class="slideshow_container">
	<!--- Slideshow stuff goes here -->
	<div id="slides">
	  <div class="slides_container">
		<div>
		  <img src="<?php echo get_stylesheet_directory_uri() ?>/slideshow/test1.jpg" width="922" height="279" alt="Slide 1">
		</div>
		<div>
		  <img src="<?php echo get_stylesheet_directory_uri() ?>/slideshow/test2.jpg" width="922" height="279" alt="Slide 2">
		</div>
		<div>
		  <img src="<?php echo get_stylesheet_directory_uri() ?>/slideshow/test3.jpg" width="922" height="279" alt="Slide 3">
		</div>
		<div>
		  <img src="<?php echo get_stylesheet_directory_uri() ?>/slideshow/test4.jpg" width="922" height="279" alt="Slide 4">
		</div>
	  </div>
	</div>
	<!-- End slideshow stuff -->
</div>
